spring:
  application:
    name: diet-manager

  datasource:
    url: jdbc:h2:mem:diet-manager;MODE=MySQL;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  sql:
    init:
      mode: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080
